import { Category, MealType, MenuItem, TaxRate } from './types';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: 'Samosa (2 Pcs)',
    description: 'Crispy pastry filled with spiced potatoes and peas, served with chutney.',
    category: Category.STARTER,
    type: MealType.VEG,
    price: 80.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/samosa/400/300',
  },
  {
    id: 'm2',
    name: 'Paneer Tikka',
    description: 'Marinated cottage cheese cubes grilled with vegetables, smoky flavor.',
    category: Category.STARTER,
    type: MealType.VEG,
    price: 250.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/paneertikka/400/300',
  },
  {
    id: 'm3',
    name: 'Chicken Tikka',
    description: 'Succulent chicken pieces marinated in spices and grilled to perfection.',
    category: Category.STARTER,
    type: MealType.NON_VEG,
    price: 300.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/chickentikka/400/300',
  },
  {
    id: 'm4',
    name: 'Butter Chicken',
    description: 'Creamy tomato-based curry with tender tandoori chicken pieces.',
    category: Category.MAIN,
    type: MealType.NON_VEG,
    price: 450.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/butterchicken/400/300',
  },
  {
    id: 'm5',
    name: 'Paneer Butter Masala',
    description: 'Rich and creamy curry with soft paneer (cottage cheese) cubes.',
    category: Category.MAIN,
    type: MealType.VEG,
    price: 400.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/paneermasala/400/300',
  },
  {
    id: 'm6',
    name: 'Dal Makhani',
    description: 'Slow-cooked black lentils in a rich, buttery, and creamy sauce.',
    category: Category.MAIN,
    type: MealType.VEG,
    price: 320.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/dalmakhani/400/300',
  },
  {
    id: 'm7',
    name: 'Garlic Naan',
    description: 'Soft leavened bread baked in a tandoor, brushed with garlic butter.',
    category: Category.SIDE, // Changed from DRINK to SIDE for bread
    type: MealType.VEG,
    price: 60.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/garlicnaan/400/300',
  },
  {
    id: 'm8',
    name: 'Basmati Rice',
    description: 'Fragrant long-grain rice, a perfect accompaniment to curries.',
    category: Category.SIDE, // Added Rice as SIDE
    type: MealType.VEG,
    price: 100.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/basmatirice/400/300',
  },
  {
    id: 'm9',
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice cooked with spiced chicken, served with raita.',
    category: Category.MAIN, // Biryani is a main course
    type: MealType.NON_VEG,
    price: 380.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/chickenbiryani/400/300',
  },
  {
    id: 'm10',
    name: 'Gulab Jamun (2 Pcs)',
    description: 'Deep-fried milk solids soaked in a rose-flavored sugar syrup.',
    category: Category.DESSERT,
    type: MealType.VEG,
    price: 90.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/gulabjamun/400/300',
  },
  {
    id: 'm11',
    name: 'Mango Lassi',
    description: 'Refreshing yogurt drink blended with sweet mango pulp.',
    category: Category.DRINK,
    type: MealType.VEG,
    price: 120.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/mangolassi/400/300',
  },
  {
    id: 'm12',
    name: 'Masala Chai',
    description: 'Traditional Indian spiced tea with milk.',
    category: Category.DRINK,
    type: MealType.VEG,
    price: 70.00,
    availability: true,
    imageUrl: 'https://picsum.photos/seed/masalachai/400/300',
  },
  {
    id: 'm13',
    name: 'Tomato Soup',
    description: 'Creamy tomato soup with crunchy bread croutons.',
    category: Category.SOUPS,
    type: MealType.VEG,
    price: 120.00,
    availability: true,
    imageUrl: '/assets/menu/tomato-soup.png',
  },
  {
    id: 'm14',
    name: 'Sweet Corn Soup',
    description: 'Comforting soup with creamy corn and minced vegetables.',
    category: Category.SOUPS,
    type: MealType.VEG,
    price: 130.00,
    availability: true,
    imageUrl: '/assets/menu/sweetcorn-soup.png',
  },
  {
    id: 'm15',
    name: 'Lemon Coriander Soup',
    description: 'Refreshing clear soup with vitamin-C rich lemon and fresh coriander.',
    category: Category.SOUPS,
    type: MealType.VEG,
    price: 140.00,
    availability: true,
    imageUrl: '/assets/menu/lemon-coriander-soup.png',
  },
  {
    id: 'm16',
    name: 'Onion Bhaji',
    description: 'Crispy deep-fried onion fritters with chickpea flour and spices.',
    category: Category.STARTER,
    type: MealType.VEG,
    price: 150.00,
    availability: true,
    imageUrl: '/assets/menu/onion-fritters.png',
  },
  {
    id: 'm17',
    name: 'Veg Spring Rolls',
    description: 'Crispy rolls filled with sautéed vegetables and glass noodles.',
    category: Category.STARTER,
    type: MealType.VEG,
    price: 180.00,
    availability: true,
    imageUrl: '/assets/menu/veg-spring-rolls.png',
  },
  {
    id: 'm18',
    name: 'Chicken 65',
    description: 'Spicy, deep-fried chicken pieces tempered with curry leaves and chilies.',
    category: Category.STARTER,
    type: MealType.NON_VEG,
    price: 320.00,
    availability: true,
    imageUrl: '/assets/menu/chicken-65.png',
  },
  {
    id: 'm19',
    name: 'Paneer 65',
    description: 'Crispy paneer cubes tossed in a spicy South Indian tempering.',
    category: Category.STARTER,
    type: MealType.VEG,
    price: 280.00,
    availability: true,
    imageUrl: '/assets/menu/fried-panner.png',
  },
  {
    id: 'm20',
    name: 'Baingan Bharta',
    description: 'Smoky roasted eggplant mashed and cooked with onions and tomatoes.',
    category: Category.MAIN,
    type: MealType.VEG,
    price: 280.00,
    availability: true,
    imageUrl: '/assets/menu/baingan-bharta.png',
  },
  {
    id: 'm21',
    name: 'Palak Paneer',
    description: 'Fresh spinach puree with soft paneer cubes and mild spices.',
    category: Category.MAIN,
    type: MealType.VEG,
    price: 360.00,
    availability: true,
    imageUrl: '/assets/menu/palak-paneer.png',
  },
  {
    id: 'm22',
    name: 'Chana Masala',
    description: 'Chickpeas cooked in a tangy and spicy tomato-based gravy.',
    category: Category.MAIN,
    type: MealType.VEG,
    price: 250.00,
    availability: true,
    imageUrl: '/assets/menu/chana-masala.png',
  },
  {
    id: 'm23',
    name: 'Fish Curry',
    description: 'Coastal style fish curry cooked in a coconut and tamarind gravy.',
    category: Category.MAIN,
    type: MealType.NON_VEG,
    price: 450.00,
    availability: true,
    imageUrl: '/assets/menu/goan-fish-curry.png',
  },
  {
    id: 'm24',
    name: 'Tandoori Roti',
    description: 'Whole wheat flatbread baked in a traditional clay oven.',
    category: Category.SIDE,
    type: MealType.VEG,
    price: 30.00,
    availability: true,
    imageUrl: '/assets/menu/tandoori-roti.png',
  },
  {
    id: 'm25',
    name: 'Lachha Paratha',
    description: 'Multi-layered flaky whole wheat bread brushed with ghee.',
    category: Category.SIDE,
    type: MealType.VEG,
    price: 60.00,
    availability: true,
    imageUrl: '/assets/menu/lachha-paratha.png',
  },
  {
    id: 'm26',
    name: 'Boondi Raita',
    description: 'Whisked yogurt with crispy gram flour droplets and roasted cumin.',
    category: Category.SIDE,
    type: MealType.VEG,
    price: 80.00,
    availability: true,
    imageUrl: '/assets/menu/boondi-raita.png',
  },
  {
    id: 'm27',
    name: 'Rasgulla (2 Pcs)',
    description: 'Soft and spongy cottage cheese balls soaked in sugar syrup.',
    category: Category.DESSERT,
    type: MealType.VEG,
    price: 80.00,
    availability: true,
    imageUrl: '/assets/menu/rasulla.png',
  },
  {
    id: 'm28',
    name: 'Jalebi (4 Pcs)',
    description: 'Spiral crispy fritters soaked in cardamom-flavored sugar syrup.',
    category: Category.DESSERT,
    type: MealType.VEG,
    price: 100.00,
    availability: true,
    imageUrl: '/assets/menu/Jalebi.png',
  },
];

export const INITIAL_TAX_RATES: TaxRate[] = [
  { name: 'GST', percentage: 0.05 }, // 5% GST for most restaurant services in India
  { name: 'Service Charge', percentage: 0.05 }, // 5% (optional, if applicable)
];

export const AVATAR_LISTENING_GIF = '/assets/avatars/lisa_chef.png'; // Premium generated Chef visual
export const AVATAR_IDLE_IMAGE = '/assets/avatars/lisa_chef.png'; // Premium generated Chef visual

export const ADMIN_USERNAME = 'admin';
export const ADMIN_PASSWORD = 'admin';
export const KITCHEN_USERNAME = 'chef';
export const KITCHEN_PASSWORD = 'chef';